### ISSUE TITLE
Can not gomi into system recycle bin if there is a file with same name

### ISSUE THREAD

**Issue by LSChyi** [b4b4r07/gomi#14]
If using the option --system on MacOS, gomi can not handle putting the second file into recycle bin if there is already file with same name in it, and the message is:

```
gomi:  already exists
```

 However, the behavior of MacOS for putting the file with same name into the recycle bin is to rename the latest file with a timestamp suffix to distinguish and is able to handle it.

**Comment by LinxiFan** [comment]
Where is the `--system` option? I don't find it on the command line or in the source code. Was it removed in the latest release?

**Comment by LSChyi** [comment]
@LinxiFan it is being removed after a big code change.
