### ISSUE TITLE
Homebrew support?

### ISSUE THREAD

**Issue by micnncim** [b4b4r07/gomi#16]
I'm very glad to see recent cool updates in `gomi` 👍 

BTW, do you have a plan to support distribution by Homebrew? Some macOS users (sure, including me) will get benefit. And also it's available by GoReleaser so you don't need to take a big effort (or I'll do if you want).

You may already know... https://goreleaser.com/customization/#Homebrew

**Comment by b4b4r07** [comment]
Thank you for the opening issue!

Yeah I know that GoReleaser feature. And also I have a plan to support Homebrew tap. It’s next task in this tool. Of course pull request is also welcome. Thanks

**Comment by micnncim** [comment]
Understood. Thank you!

**Comment by b4b4r07** [comment]
As you already know,

Now you can install it via homebrew!

```console
$ brew install b4b4r07/tap/gomi
...
...
==> Tapping b4b4r07/tap
Cloning into '/usr/local/Homebrew/Library/Taps/b4b4r07/homebrew-tap'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 8 (delta 0), reused 0 (delta 0), pack-reused 4
Unpacking objects: 100% (8/8), done.
Tapped 1 formula (32 files, 25KB).
==> Installing gomi from b4b4r07/tap
==> Downloading https://github.com/b4b4r07/gomi/releases/download/v1.1.1/gomi_darwin_x86_64.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/34890657/37949a00-47c0-11ea-8302-5e1608ef08e6?X-Amz-Algorithm=AWS4-HMAC-S
######################################################################## 100.0%
🍺  /usr/local/Cellar/gomi/1.1.1: 4 files, 8.2MB, built in 16 seconds
```

**Comment by micnncim** [comment]
Cool! Thank you for notification😄
