### ISSUE TITLE
fオプションを指定すると稀に削除が出来なくなる

### ISSUE THREAD

**Issue by yasuno0327** [b4b4r07/gomi#21]
`gomi -rf hoge`などfオプションを指定して削除を実行すると稀に削除が出来ないことがあります。
[こちら](https://github.com/b4b4r07/gomi/blob/9ab4422ced6f06c41f89a5b14a19a46630221cec/main.go#L220)でfオプションを指定している場合のみゴルーチンの実行を待たないため、os.Renameが実行されないことが原因のようです。

```main.go
eg.Go(func() error {
			_, err := os.Stat(arg)
			if os.IsNotExist(err) {
				return fmt.Errorf("%s: no such file or directory", arg)
			}
			file, err := makeFile(groupID, arg)
			if err != nil {
				return err
			}

			time.Sleep(time.Second * 10)

```

上記のようにゴルーチン内にスリープ処理を挟むと削除されなくなります。

**Comment by b4b4r07** [comment]
遅くなりすみません

ありがとうございます。確認します

**Comment by b4b4r07** [comment]
Closing as #25
