### ISSUE TITLE
Please bump golang.org/x/sys dependency

### ISSUE THREAD

**Issue by clausecker** [b4b4r07/gomi#29]
The version of `golang.org/x/sys` you depend on is too old to support new platforms such as riscv64-freebsd.  Please bump it to the most recent version to support a build on such platforms.

**Comment by b4b4r07** [comment]
Thanks. Updated

**Comment by clausecker** [comment]
It does not seem like you actually updated the dependency.  Try

    go get golang.org/x/sys@latest

in your repository to update it.

**Comment by b4b4r07** [comment]
I did

**Comment by clausecker** [comment]
Thank you.
