### ISSUE TITLE
複数のマウントポイント上で使えるようになるとうれしいです on Linux

### ISSUE THREAD

**Issue by Nobutarou** [b4b4r07/gomi#3]
マウントポイントの違うところでも使いたいです。
 invalid cross-device link

**Comment by b4b4r07** [comment]
例えばどのような想定（状況など）ですか？

**Comment by Nobutarou** [comment]
例えば、/home が sda1 にマウントされているのですが、空容量などの関係で、sdb1 を例えば /data などにマウントして、もっぱら作業は
sdb1 の方でしているような状況です。

2016年4月18日月曜日、BABAROT<notifications@github.com>さんは書きました:

**Comment by b4b4r07** [comment]
なるほど、意外と需要ありそうでいいですね。ただ、他リポジトリにおけるタスクが多いため、実装には時間がかかりそうです。

**Comment by Nobutarou** [comment]
いえいえ、わざわざご丁寧にありがとうございます。
