### ISSUE TITLE
Cannot remove including slushes folder

### ISSUE THREAD

**Issue by sachin21** [b4b4r07/gomi#7]
# Problem Summary
Occurred following error.
```
$ gomi "--skip-test-unit"
--: unknown option
```

It seems like judged options

## Opnion
grep command has solution.
```
ps aux | grep -- "--hoge"
```

I think gomi should be able to `--` option.

# System Information
- Zsh: zsh 5.2 (x86_64-unknown-linux-gnu)
- gomi: v0.1.7

**Comment by b4b4r07** [comment]
Maybe I could implement that feature. However, I have not checked whether it works nicely.

**Comment by sachin21** [comment]
:pray:

**Comment by sachin21** [comment]
Ahh, I forgot to say.
GNU rm command also has same an implementation.

**Comment by b4b4r07** [comment]
What do you mean? Is there anything else I should do?

**Comment by sachin21** [comment]
No, I just write additional Information.

**Comment by b4b4r07** [comment]
merged

**Comment by sachin21** [comment]
Thank you so much!
